spring.application.name=smart-interview-pre-platform
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_o9xdY9nSJlY2HK8x19F@mysql-2539e6d-anujyadav221307vns-1a7f.b.aivencloud.com:26013/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_o9xdY9nSJlY2HK8x19F
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8282
gemini.api.key=AQ.Ab8RN6K6BFcpBCqZuu41WRt1w3OtNVoTGCIuvNPBhiZFAw9b6A