spring.application.name=smart-interview-pre-platform
spring.datasource.url=jdbc:mysql://localhost:3306/interview_prep_db
spring.datasource.username=root
spring.datasource.password=Radha@Krishna@9005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8282
gemini.api.key=AIzaSyANyjD1uiNQMoEU55qs5QbCUt2QlfBpMDM
